// commands/antibot.js
let antiBotEnabled = {};
let botStrikeCount = {}; // Compte les infractions par utilisateur

module.exports = {
  name: 'antibot',
  description: 'Supprime automatiquement les messages détectés comme automatisés par des bots (on/off) + kick à 3 infractions',
  async execute({ client, message, args }) {
    try {
      if (!message.isGroup) {
        return client.sendMessage(message.from, { text: '❌ Cette commande fonctionne uniquement dans un groupe.' });
      }

      const groupMetadata = await client.groupMetadata(message.from);
      const participants = groupMetadata.participants;

      const isUserAdmin = participants.find(
        p => p.id === message.sender && (p.admin === 'admin' || p.admin === 'superadmin')
      );
      if (!isUserAdmin) {
        return client.sendMessage(message.from, { text: '🔒 Seuls les administrateurs peuvent utiliser cette commande.' });
      }

      if (!args[0]) {
        return client.sendMessage(message.from, { text: 'Utilisation : *!antibot on* ou *!antibot off*' });
      }

      if (args[0] === 'on') {
        antiBotEnabled[message.from] = true;
        botStrikeCount[message.from] = {};
        client.sendMessage(message.from, { text: '✅ Anti-bot activé pour ce groupe.' });
      } else if (args[0] === 'off') {
        antiBotEnabled[message.from] = false;
        botStrikeCount[message.from] = {};
        client.sendMessage(message.from, { text: '❌ Anti-bot désactivé pour ce groupe.' });
      }
    } catch (err) {
      console.error('Erreur antibot.js:', err);
      client.sendMessage(message.from, { text: '❌ Erreur lors de l’activation/désactivation de l’anti-bot.' });
    }
  },

  async onMessage({ client, message }) {
    try {
      if (!message.isGroup || !antiBotEnabled[message.from]) return;

      // Détection basique de messages suspects (messages générés par bots)
      const text = message.body?.toLowerCase() || '';
      const probableBotPatterns = [
        'type !help', 'use /menu', 'generated by', '🤖', 'bot command', 'prefix !', 'prefix .'
      ];

      const isSuspectBot =
        probableBotPatterns.some(pattern => text.includes(pattern)) ||
        message.sender.includes('bot') || // Si le JID contient "bot"
        (message.message?.buttonsMessage || message.message?.listMessage); // Messages interactifs typiques de bots

      if (isSuspectBot) {
        await client.sendMessage(message.from, { delete: message.key });

        if (!botStrikeCount[message.from]) botStrikeCount[message.from] = {};
        if (!botStrikeCount[message.from][message.sender]) botStrikeCount[message.from][message.sender] = 0;
        botStrikeCount[message.from][message.sender]++;

        const infractions = botStrikeCount[message.from][message.sender];

        const botImage = 'https://files.catbox.moe/jvuqi0.jpg';
        let caption = `
┌───────────────────
│ 🅥︎🅐︎🅜︎🅟︎🅘︎🅡︎🅔︎  Ⓜ︎Ⓓ︎
└───────────────────
🌐𝐕𝐄𝐑𝐒𝐈𝐎𝐍 : *1.0*
🖊️𝚃𝚈𝙿𝙴 : 𝙼𝙸𝙽𝙸-𝙱𝙾𝚃
🌹⃝━❮ 𝓹𝓻𝓸𝓶𝓾𝓽 𝓹𝓪𝓻 𝓳𝓮𝓷𝓲𝓯𝓮𝓻 𝔁𝓶
__________________________________
🤖 Bots interdits détectés
🥹 Stop please (${infractions}/3)
__________________________________
`;

        await client.sendMessage(message.from, {
          image: { url: botImage },
          caption
        });

        if (infractions >= 3) {
          await client.groupParticipantsUpdate(message.from, [message.sender], 'remove');

          const kickCaption = `
┌───────────────────
│ 🅥︎🅐︎🅜︎🅟︎🅘︎🅡︎🅔︎  Ⓜ︎Ⓓ︎
└───────────────────
🌐𝐕𝐄𝐑𝐒𝐈𝐎𝐍 : *1.0*
🖊️𝚃𝚈𝙿𝙴 : 𝙼𝙸𝙽𝙸-𝙱𝙾𝚃
🌹⃝━❮ 𝓹𝓻𝓸𝓶𝓾𝓽 𝓹𝓪𝓻 𝓳𝓮𝓷𝓲𝓯𝓮𝓻 𝔁𝓶
__________________________________
💢 @${message.sender.split('@')[0]} a été expulsé pour spam de messages bot (3/3)
__________________________________
`;
          await client.sendMessage(message.from, {
            image: { url: botImage },
            caption: kickCaption,
            mentions: [message.sender]
          });
        }
      }
    } catch (err) {
      console.error('Erreur détection antibot:', err);
    }
  }
};
